# Generated by Django 4.2.3 on 2023-08-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trineer',
            fields=[
                ('t_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
